### ISSUE TITLE
No output from optimizer

### ISSUE THREAD

**Issue by mskogly** [euphy/polargraph#2]
This is interresting: When running the default map.txt queue it works fine. When I try to run a queue I saved myself, the script runs, it calculates savings, and it spits out all the commands. But the resulting file is empty. I first thought it was because it was places in my dropbox folder, and that the issue was with writing permissions, but the result is the same when running it in another folder. 

Can you try to run the included txt, and see if you can figure out what it is?

I have tried two other vectors, with the same empty outout. 

[heiafotballlogo.txt](https://github.com/euphy/polargraph/files/515719/heiafotballlogo.txt)

**Comment by euphy** [comment]
Hiya, just tried it here, using python 2.7, and it seemed to work ok:

$ python process.py heiafotballlogo.txt > heiafotballlogo_optimised.txt
Total Glyphs: 64
Initial penup distance:    201476
Initial total distance:    914300
Deduped penup distance:    201476
Deduped total distance:    914300
Sorted penup distance:     247472
Sorted total distance:     960296
Greedy penup (i=0)         100217
Greedy total (i=0)         813041

And I can load the queue into the controller.
I have found a bug in the controller however, where the queue doesn't actually show up until I clock "import queue" again, and cancel the dialog the second time around. Not sure what that's about.

Also your issue is added to the wrong project - it's really unclear what version of the optimiser you're using. (https://github.com/euphy/polargraph-optimizer or the original https://github.com/ezheidtmann/polargraph-optimizer), and you haven't said what version of python you're using.

**Comment by euphy** [comment]
No response, so closing.
