### ISSUE TITLE
Suddenly the gondola is moved outside drawing range and motor keeps rotating

### ISSUE THREAD

**Issue by bibo750four** [euphy/polargraph#8]
Hello,
I have an unclear problem during a complex drawing, that seems to happen in different points of the drawing in a reproducible way. The drawing is going well but suddenly the gondola is moved to a low point of the board, outside the drawing range.
The last command in the queue seems to be a valid point in the drawing range, so it is not clear why the movement is wrong.
I am using polargraph controller last build with mac os binaries and an Arduino Uno with CNC Shield.
![CB750Fo
[terza.txt](https:
[default.properties.txt](https://github.com/euphy/polargraph/files/8079795/default.properties.txt)
//github.com/euphy/polargraph/files/8079788/terza.txt)
ur_verticale](https://user-images.githubusercontent.com/73854690/154262990-06d20f9a-6e03-4007-acd9-d5cbcd0d3bc5.svg)
[Print_error.txt](https://github.com/euphy/polargraph/files/8079782/Print_error.txt)
Btw the polargraph SW/HW is great, congratulations for creating it!
[default.properties.txt](https://github.com/euphy/polargraph/files/8079807/default.properties.txt)

**Comment by euphy** [comment]
Hi, thanks! And thanks for the properties, image and error notes - very useful. I was running the controller from source and couldn't even get this to draw the vector file! Kept on locking up and crashing. Eventually I've commented a line out (https://github.com/euphy/polargraphcontroller/blob/master/drawing.pde#L920) and finally it could generate the command queue for the drawing.

Doing a "draw vector" and then saving out the command queue gives me a 194,593 line file, and the line that yours has broken down on is on 68,636, about a third of the way through. The position is 4756, 4719.

Unfortunately I agree - I don't see anything special about that point, it is lower than the home point (which is 4280, 4092) which means it's also on the drawing area. The polargraph controller draws the points in the SVG in the same sequence that the points are in the SVG file. In this file, that's roughly in a series of vertical strips, points from each strip being drawn from top to bottom. The only remarkable thing about that point that breaks is that it's the first point in a new row, it's the top of a new row so it follows a long vertical move.

The C14 command means "lift pen", then the command to move to 4656, 4719 is dispatched. I'm assuming you reboot the machine at that point to stop it from making a mess?

I don't have a working machine to test this on, but the trouble I had loading this file even into the polargraph controller makes me wonder if it's the controller crashing out somewhere or corrupting the command stream.

You could try the polargraph vector optimizer tool to re-sequence the drawing into a different order. This _might_ do something, but might just move the problem somewhere else!

I've attached an optimised version of the command queue, if you load it up into the controller (queue tab -> import queue) and wait for it to load then you can see it's the same commands in a different order. It's usually draws much faster!

So even this doesn't "fix" the problem, then it's possible that the faster draw time helps.  I'd try that. There's a page here https://github.com/euphy/polargraph/wiki/Vector-Optimizer about the optimizer, I didn't make it but it's really good.

For really long drawings, I stopped relying on the Polargraph controller itself just because it was unreliable, and started using this little script instead - https://github.com/euphy/polargraph/wiki/Standalone-command-queue-runner.

Both the things above are python code so you'll need python installed. Of course eventually I started drawing stuff from SD card instead of using the serial port so much - I found the serial connection between my (windows) machine and the UNO to be too unreliable for any long drawing.

Good luck!

[queue-optimized.txt](https://github.com/euphy/polargraph/files/8092822/queue-optimized.txt)

**Comment by bibo750four** [comment]
Hello Sandy,

Thanks a lot for taking the time to look at the problem in detail. I have
installed and run the vector optimizer, it really improved the queue a lot.
I also have an unused Raspberry Pi so I could try the standalone command
queue runner.
Anyway, I will try my luck first, by restarting the drawing from the point
that crashed (I exported the queue at that point) and using an optimized
queue.

I will keep you informed.

Ciao
Marco

**Comment by bibo750four** [comment]
Hi Sandy,

With the optimized queue all went well, I could complete the drawing without further errors!

Thanks again. For the next complex files I will use the optimizer and try the standalone queue runner.

Have a nice weekend
Marco




> Il giorno 18.02.2022, alle ore 08:12, Marco De Bei ***@***.***> ha scritto:
> 
> Hello Sandy,
> 
> Thanks a lot for taking the time to look at the problem in detail. I have installed and run the vector optimizer, it really improved the queue a lot. I also have an unused Raspberry Pi so I could try the standalone command queue runner. 
> Anyway, I will try my luck first, by restarting the drawing from the point that crashed (I exported the queue at that point) and using an optimized queue. 
> 
> I will keep you informed.
> 
> Ciao
> Marco
> 
>

**Comment by euphy** [comment]
That's really good news! Sorry it's not a "proper" fix, but it's a workaround. Happy scribbling!
